"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.orderRuter = void 0;
const express_1 = __importDefault(require("express"));
const auth_1 = __importDefault(require("../../middlerware/auth"));
const order_controller_1 = require("./order.controller");
// import auth from "../../middlerware/auth";
// import { userController } from "./user.controller";
// import * as UserController from '../controllers/user.controller';
const router = express_1.default.Router();
router.get("/", auth_1.default, order_controller_1.orderController.orderGetController);
router.get("/:id", auth_1.default, order_controller_1.orderController.OrdersforSpecificCustomersController);
router.get("/api/v1/orders/:orderId", auth_1.default, order_controller_1.orderController.OrdersforSpecificCustomersController);
// router.patch("/:id", auth, userController.userUpdateController);
// router.delete("/:id", auth, userController.deleteUserController);
// router.post("/signup", userController.userCreateController);
router.post("/create-order", auth_1.default, order_controller_1.orderController.orderCreateController);
exports.orderRuter = router;
